# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Alti/multiplier/multiplier.cache/wt [current_project]
set_property parent.project_path C:/Users/Alti/multiplier/multiplier.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Alti/multiplier/multiplier.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/CLA_adder.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/new/Eight_bit_rgstr.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/and_AB.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/bcd_to_7seg.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/clk_gen.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/debounce2.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/half_adder.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/Downloads/led_mux.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/imports/new/multiplier.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/new/registerA.v
  C:/Users/Alti/multiplier/multiplier.srcs/sources_1/new/top_level_for_multiplier.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alti/multiplier/multiplier.srcs/constrs_1/new/reg_multiplier.xdc
set_property used_in_implementation false [get_files C:/Users/Alti/multiplier/multiplier.srcs/constrs_1/new/reg_multiplier.xdc]


synth_design -top top_level_for_multiplier -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_level_for_multiplier.dcp

catch { report_utilization -file top_level_for_multiplier_utilization_synth.rpt -pb top_level_for_multiplier_utilization_synth.pb }
